apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: items-microservice
  template:
    metadata:
      labels:
        app: items-microservice
    spec:
      containers:
        - image: rsouser/items-microservice
          name: items-microservice
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: gke-rso-secrets
                  key: db_host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: gke-rso-secrets
                  key: db_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: gke-rso-secrets
                  key: db_user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: gke-rso-secrets
                  key: db_pass
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://${DB_HOST}/${DB_NAME}?user=${DB_USER}@rso-db&password=${DB_PASS}
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: ${DB_USER}
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: ${DB_PASS}
            - name: KUMULUZEE_SERVER_HTTP_PORT
              value: "8001"
            - name: KUMULUZEE_ENV_NAME
              value: "dev"
            - name: KUMULUZEE_NAME
              value: "items-microservice"
            - name: KUMULUZEE_SERVER_BASEURL
              value: http://20.76.184.237/items-service/
            - name: KUMULUZEE_OPENAPIMP_UI_SPECIFICATIONSERVER
              value: http://20.76.184.237/items-service/
            - name: KUMULUZEE_OPENAPIMP_SERVERS
              value: http://20.76.184.237/items-service/
          ports:
            - containerPort: 8001
              name: server
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: items-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: items-microservice
