kumuluzee:
  name: items-microservice
  env:
    name: dev
  version: 1.0.0
  server:
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ItemDS
      connection-url: jdbc:postgresql://localhost:5432/rso_db
      username: dbuser
      password: postgres
      pool:
        max-size: 20
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ItemDS
      disk-space-health-check:
        threshold: 100000000
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
    web-instrumentation:
      - name: items-endpoint
        url-pattern: /v1/images/*
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    consul:
      agent: http://localhost:8500
  graphql:
    schema:
      include-scalars: true
      include-schema-definition: true
      include-directives: true
      include-introspection-types: true
    metrics:
      enabled: true
  dev:
    scan-libraries:
      - items-microservice-services
      - items-microservice-models
      - items-microservice-lib
